defmodule DranWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :dran

  # The session is stored in an encrypted cookie (contents can be neither
  # read nor tampered with by the client). Salts and lifetime are
  # runtime-configurable via env vars. SESSION_COOKIE_SECURE=true forces the
  # Secure flag (HTTPS-only cookie); unset = Plug default (secure only when
  # the request itself is HTTPS, so HTTP deploys keep working).
  session_secure =
    case System.get_env("SESSION_COOKIE_SECURE") do
      v when v in ["true", "1"] -> [secure: true]
      v when v in ["false", "0"] -> [secure: false]
      _ -> []
    end

  # The dev fallbacks are TWO DIFFERENT values and are not used in prod:
  # runtime.exs requires both salts from the environment when config_env() ==
  # :prod. Equal salts (the old default: one single string for both) make the
  # cookie forgeable/decryptable — see the family standard, SPEC-config.md
  # §Session and cookies.
  @session_options [
                     store: :cookie,
                     key: "_dran_key",
                     signing_salt:
                       System.get_env("SESSION_SIGNING_SALT", "dran-dev-signing-salt"),
                     encryption_salt:
                       System.get_env("SESSION_ENCRYPTION_SALT", "dran-dev-encryption-salt"),
                     same_site: "Lax",
                     http_only: true,
                     # Sliding renewal: the cookie is re-issued with a fresh
                     # max_age on every response, so an active person stays in
                     # and an idle browser expires. Without it the lifetime is
                     # absolute.
                     renew: true,
                     max_age:
                       String.to_integer(System.get_env("SESSION_MAX_AGE_SECONDS", "31536000"))
                   ] ++ session_secure

  # connect_info on BOTH entries (websocket and longpoll): the socket needs the
  # session, and peer_data/user_agent are what the app reads for the IP and the
  # user agent of a LiveView. A longpoll fallback without them behaves
  # differently from the websocket.
  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options, peer_data: true, user_agent: true]],
    longpoll: [connect_info: [session: @session_options, peer_data: true, user_agent: true]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  #
  # `only` matches the *first path segment exactly*, but `phx.digest` renames
  # top-level files (logo.png -> logo-<hash>.png, favicon.ico -> favicon-<hash>.ico,
  # robots.txt -> robots-<hash>.txt). Without `only_matching` those digested
  # names are rejected, the request falls through to the router and gets a 302
  # to /login — so `~p"/logo.png"` (the in-app header logo) renders broken in
  # production. `only_matching` adds prefix matching for the digestable
  # top-level stems (files under an allowed directory, e.g. assets/…, already
  # match their directory prefix and need no entry here).
  plug Plug.Static,
    at: "/",
    from: :dran,
    gzip: not code_reloading?,
    only: DranWeb.static_paths(),
    only_matching: ~w(favicon logo robots),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :dran
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library(),
    # Explicit body-size limits. The multipart cap (200MB) is set above the app's
    # upload max (UPLOADS_MAX_SIZE, default 100MB); urlencoded/json stay small
    # so a huge form/API body is rejected at the parser, before any app code runs.
    length: 2_000_000,
    multipart_length: 200_000_000

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug DranWeb.Router
end
