import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :dran, DranWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# Note `:force_ssl` is required to be set at compile-time.
#
# Set DISABLE_FORCE_SSL=1 at build time to skip this entirely. Use this when
# serving the app over plain HTTP (e.g. behind a NetBird / Wireguard tunnel
# without a TLS terminator in front).
endpoint_config =
  if System.get_env("DISABLE_FORCE_SSL") == "1" do
    []
  else
    [
      force_ssl: [
        rewrite_on: [:x_forwarded_proto],
        exclude: [
          # paths: ["/health"],
          hosts: ["localhost", "127.0.0.1"]
        ]
      ]
    ]
  end

config :dran, DranWeb.Endpoint, endpoint_config

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
