import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :dran, DranWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# force_ssl is configured at runtime in config/runtime.exs so it can be
# toggled via the DISABLE_FORCE_SSL env var without a rebuild. We set a
# compile-time default here to avoid the "different value at compile vs
# runtime" validation error when the release boots.
config :dran, DranWeb.Endpoint, force_ssl: [rewrite_on: [:x_forwarded_proto]]

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
